# Fase 1 do projeto da disciplina: Ciência de Dados e Inteligência Artificial - PUCRS

O objetivo deste trabalho é selecionar um conjunto de dados interessante, desenvolver um projeto inicial sobre ele com a ferramenta Orange Data Mining e identificar oportunidades em ciência de dados com ele. Para tanto, procurem algum conjunto de dados que vocês se sintam motivados a explorar. O conjunto selecionado deve ter pelo menos 1.000 linhas e pelo menos 10 colunas totalmente preenchidas (sem valores faltantes) e, principalmente, deve ter um atributo alvo, categórico ou numérico.

#### Enunciado:
1. Procurem um conjunto de dados com, pelo menos, 1.000 linhas e 10 colunas, e que tenha um atributo alvo categórico ou numérico.
2. Façam a carga no Orange Data Mining para ajudar na exploração.
3. Transcrevam a síntese do conjunto de dados como apresentado em sua origem.
4. Em até 3 parágrafos, expliquem o interesse em explorá-lo.
5. Sobre o conjunto de dados escolhido:
- Qual a finalidade do conjunto de dados?
- Quantas linhas e quantas colunas o conjunto de dados tem?
- Qual o formato que ele é disponibilizado? (CSV, JSON, XLSX, etc)

6. Escolham pelo menos 10 colunas totalmente preenchidas (as mais importantes) e, para cada coluna (inclusive para a coluna alvo):
- Qual o nome e o que representa?
- Qual o tipo de dados? Nominal/Ordinal/Numérico/Data e/ou hora?
- Quais são os valores considerados válidos?
- Quantos valores distintos aparecem na coluna?
- Qual o menor e o maior valor, e qual a moda?
- Os valores da coluna são numéricos? Qual a média e qual o desvio-padrão? Qual a mediana?

7. Qual a oportunidade para um projeto de ciência de dados foi identificada? Justificar a resposta!



8. O que você deve entregar nesta fase:  Documento em PDF/DOCX (desenvolvido a partir do modelo de template disponibilizado)  com a documentação de todas as atividades feitas e o link para o conjunto de dados escolhido. No caso de ter sido feito um recorte/amostragem do conjunto original, documentar quais foram os passos feitos para produzir o recorte.

### Dataset: Students Performance Dataset:

**Link:** https://www.kaggle.com/datasets/rabieelkharoua/students-performance-dataset

**Autor:** Rabie El Kharoua

**DOI:** 10.34740/kaggle/ds/5195702


### Índice
Os dados sobre os estudantes foram coletados considerando as categorias abaixo:

- Informações dos Estudantes
 - ID do Estudante
 - Detalhes Demográficos (idade, gênero, etnia, educação dos pais)
 - Hábitos de Estudo (tempo de estudo semanal, faltas e aulas de reforço)
- Envolvimento dos Pais (apoio dos pais)
- Atividades Extracurriculares (atividades extracurriculares, esportes, música e voluntariado)
- Desempenho Acadêmico (GPA)
- Variável Alvo: Classificação de Notas

### Dicionário do Conjunto de Dados (Por Coluna)

- **ID do Estudante:** Um identificador único atribuído a cada estudante.
- **Idade:** A idade dos estudantes varia de 15 a 18 anos.
- **Gênero:** Gênero dos estudantes, onde 0 representa Masculino e 1 representa Feminino.
- **Etnia:** A etnia dos estudantes, codificada da seguinte forma:
 - 0: Caucasiano;
 - 1: Afro-Americano;
 - 2: Asiático;
 - 3: Outro.
- **Educação dos Pais:** O nível de educação dos pais, codificado da seguinte forma:
 - 0: Nenhuma;
 - 1: Ensino Médio;
 - 2: Algum Ensino Superior;
 - 3: Bacharelado;
 - 4: Superior.
- **Tempo de Estudo Semanal:** Tempo de estudo semanal em horas, variando de 0 a 20.
- **Faltas:** Número de faltas durante o ano letivo, variando de 0 a 30.
- **Aulas de Reforço:** Status de aulas de reforço, onde 0 indica Não e 1 indica Sim.
- **Apoio dos Pais:** O nível de apoio dos pais, codificado da seguinte forma:
 - 0: Nenhum;
 - 1: Baixo;
 - 2: Moderado;
 - 3: Alto;
 - 4: Muito Alto.
- **Atividades Extracurriculares:** Participação em atividades extracurriculares, onde 0 indica Não e 1 indica Sim.
- **Esportes:** Participação em esportes, onde 0 indica Não e 1 indica Sim.
- **Música:** Participação em atividades musicais, onde 0 indica Não e 1 indica Sim.
- **Voluntariado:** Participação em voluntariado, onde 0 indica Não e 1 indica Sim.
- **GPA:** Média de Notas (Grade Point Average) em uma escala de 2,0 a 4,0, influenciada por hábitos de estudo, envolvimento dos pais e atividades extracurriculares.
- **Variável Alvo: Classificação de Notas**
- **Classificação de Notas:** Classificação das notas dos estudantes com base no GPA:
 - 0: 'A' (GPA >= 3,5);
 - 1: 'B' (3,0 <= GPA < 3,5);
 - 2: 'C' (2,5 <= GPA < 3,0);
 - 3: 'D' (2,0 <= GPA < 2,5);
 - 4: 'F' (GPA < 2,0).

In [ ]:
#Importação de bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency
import seaborn as sns
from scipy.stats import mannwhitneyu

In [ ]:
# Montando o Google Drive no ambiente do Colab.
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Caminho do arquivo
caminho_csv = '/content/drive/MyDrive/PUCRS/CienciaDeDados/Student_performance_data _.csv'

In [ ]:
# Carregando o arquivo CSV usando Pandas
df_student_performance = pd.read_csv(caminho_csv)

In [ ]:
display(df_student_performance)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,1,0,3,10.680555,2,0,4,1,0,0,0,3.455509,0.0
2388,3389,17,0,0,1,7.583217,4,1,4,0,1,0,0,3.279150,4.0
2389,3390,16,1,0,2,6.805500,20,0,2,0,0,0,1,1.142333,2.0
2390,3391,16,1,1,0,12.416653,17,0,2,0,1,1,0,1.803297,1.0
2391,3392,16,1,0,2,17.819907,13,0,2,0,0,0,1,2.140014,1.0

In [ ]:
#Resumo geral das variáveis
df_student_performance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          2392 non-null   int64
 1   Age                2392 non-null   int64
 2   Gender             2392 non-null   int64
 3   Ethnicity          2392 non-null   int64
 4   ParentalEducation  2392 non-null   int64
 5   StudyTimeWeekly    2392 non-null   float64
 6   Absences           2392 non-null   int64
 7   Tutoring           2392 non-null   int64
 8   ParentalSupport    2392 non-null   int64
 9   Extracurricular    2392 non-null   int64
 10  Sports             2392 non-null   int64
 11  Music              2392 non-null   int64
 12  Volunteering       2392 non-null   int64
 13  GPA                2392 non-null   float64
 14  GradeClass         2392 non-null   float64
dtypes: float64(3), int64(12)
memory usage: 280.4 KB

In [ ]:
#Verificando valores nulos
df_student_performance.isnull().sum()

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

In [ ]:
#Verificando linhas duplicadas pela coluna identificadora
df_student_performance['StudentID'].duplicated().sum()

0

In [ ]:
# Análise das colunas

lista_Nome_Colunas = df_student_performance.columns.tolist()

def analise_colunas(lista, df):
    for i in lista:
        print(f"Análise da Coluna: {i}")
        print("-" * 50)

        # Valores únicos
        unique_values = df[i].unique()
        print("Valores Únicos:")
        print(unique_values)
        print('\n')

        # Contar número de valores únicos
        num_unique_values = df[i].nunique()
        print("Número de Valores Únicos:")
        print(num_unique_values)
        print('\n')

        # Estatísticas descritivas
        stat_describe = pd.DataFrame(df[i].describe())
        print("Estatísticas Descritivas:")
        print(stat_describe)
        print('\n')

        # Moda
        mode_value = df[i].mode()
        print('Moda:')
        print(mode_value)
        print('\n')

        # Mediana
        median_value = df[i].median()
        print('Mediana:')
        print(median_value)
        print('\n')

        print("=" * 50)

# Executa a função
analise_colunas(lista_Nome_Colunas, df_student_performance)

Análise da Coluna: StudentID
--------------------------------------------------
Valores Únicos:
[1001 1002 1003 ... 3390 3391 3392]


Número de Valores Únicos:
2392


Estatísticas Descritivas:
         StudentID
count  2392.000000
mean   2196.500000
std     690.655244
min    1001.000000
25%    1598.750000
50%    2196.500000
75%    2794.250000
max    3392.000000


Moda:
0       1001
1       1002
2       1003
3       1004
4       1005
        ...
2387    3388
2388    3389
2389    3390
2390    3391
2391    3392
Name: StudentID, Length: 2392, dtype: int64


Mediana:
2196.5


==================================================
Análise da Coluna: Age
--------------------------------------------------
Valores Únicos:
[17 18 15 16]


Número de Valores Únicos:
4


Estatísticas Descritivas:
               Age
count  2392.000000
mean     16.468645
std       1.123798
min      15.000000
25%      15.000000
50%      16.000000
75%      17.000000
max      18.000000


Moda:
0    15
Name: Age, dtype: int64


Mediana:
16.0


==================================================
Análise da Coluna: Gender
--------------------------------------------------
Valores Únicos:
[1 0]


Número de Valores Únicos:
2


Estatísticas Descritivas:
            Gender
count  2392.000000
mean      0.510870
std       0.499986
min       0.000000
25%       0.000000
50%       1.000000
75%       1.000000
max       1.000000


Moda:
0    1
Name: Gender, dtype: int64


Mediana:
1.0


==================================================
Análise da Coluna: Ethnicity
--------------------------------------------------
Valores Únicos:
[0 2 1 3]


Número de Valores Únicos:
4


Estatísticas Descritivas:
         Ethnicity
count  2392.000000
mean      0.877508
std       1.028476
min       0.000000
25%       0.000000
50%       0.000000
75%       2.000000
max       3.000000


Moda:
0    0
Name: Ethnicity, dtype: int64


Mediana:
0.0


==================================================
Análise da Coluna: ParentalEducation
--------------------------------------------------
Valores Únicos:
[2 1 3 4 0]


Número de Valores Únicos:
5


Estatísticas Descritivas:
       ParentalEducation
count        2392.000000
mean            1.746237
std             1.000411
min             0.000000
25%             1.000000
50%             2.000000
75%             2.000000
max             4.000000


Moda:
0    2
Name: ParentalEducation, dtype: int64


Mediana:
2.0


==================================================
Análise da Coluna: StudyTimeWeekly
--------------------------------------------------
Valores Únicos:
[19.83372281 15.40875606  4.21056977 ...  6.80549964 12.41665266
 17.81990749]


Número de Valores Únicos:
2392


Estatísticas Descritivas:
       StudyTimeWeekly
count      2392.000000
mean          9.771992
std           5.652774
min           0.001057
25%           5.043079
50%           9.705363
75%          14.408410
max          19.978094


Moda:
0        0.001057
1        0.004859
2        0.008031
3        0.008206
4        0.014337
          ...
2387    19.939810
2388    19.948459
2389    19.968425
2390    19.972346
2391    19.978094
Name: StudyTimeWeekly, Length: 2392, dtype: float64


Mediana:
9.705363212574394


==================================================
Análise da Coluna: Absences
--------------------------------------------------
Valores Únicos:
[ 7  0 26 14 17 10 22  1 11 15 21  9 16 29  2 25 20  5  8 12 27 23  3 13
  6 28  4 18 19 24]


Número de Valores Únicos:
30


Estatísticas Descritivas:
          Absences
count  2392.000000
mean     14.541388
std       8.467417
min       0.000000
25%       7.000000
50%      15.000000
75%      22.000000
max      29.000000


Moda:
0    13
1    25
Name: Absences, dtype: int64


Mediana:
15.0


==================================================
Análise da Coluna: Tutoring
--------------------------------------------------
Valores Únicos:
[1 0]


Número de Valores Únicos:
2


Estatísticas Descritivas:
          Tutoring
count  2392.000000
mean      0.301421
std       0.458971
min       0.000000
25%       0.000000
50%       0.000000
75%       1.000000
max       1.000000


Moda:
0    0
Name: Tutoring, dtype: int64


Mediana:
0.0


==================================================
Análise da Coluna: ParentalSupport
--------------------------------------------------
Valores Únicos:
[2 1 3 4 0]


Número de Valores Únicos:
5


Estatísticas Descritivas:
       ParentalSupport
count      2392.000000
mean          2.122074
std           1.122813
min           0.000000
25%           1.000000
50%           2.000000
75%           3.000000
max           4.000000


Moda:
0    2
Name: ParentalSupport, dtype: int64


Mediana:
2.0


==================================================
Análise da Coluna: Extracurricular
--------------------------------------------------
Valores Únicos:
[0 1]


Número de Valores Únicos:
2


Estatísticas Descritivas:
       Extracurricular
count      2392.000000
mean          0.383361
std           0.486307
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000


Moda:
0    0
Name: Extracurricular, dtype: int64


Mediana:
0.0


==================================================
Análise da Coluna: Sports
--------------------------------------------------
Valores Únicos:
[0 1]


Número de Valores Únicos:
2


Estatísticas Descritivas:
            Sports
count  2392.000000
mean      0.303512
std       0.459870
min       0.000000
25%       0.000000
50%       0.000000
75%       1.000000
max       1.000000


Moda:
0    0
Name: Sports, dtype: int64


Mediana:
0.0


==================================================
Análise da Coluna: Music
--------------------------------------------------
Valores Únicos:
[1 0]


Número de Valores Únicos:
2


Estatísticas Descritivas:
             Music
count  2392.000000
mean      0.196906
std       0.397744
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000


Moda:
0    0
Name: Music, dtype: int64


Mediana:
0.0


==================================================
Análise da Coluna: Volunteering
--------------------------------------------------
Valores Únicos:
[0 1]


Número de Valores Únicos:
2


Estatísticas Descritivas:
       Volunteering
count   2392.000000
mean       0.157191
std        0.364057
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000


Moda:
0    0
Name: Volunteering, dtype: int64


Mediana:
0.0


==================================================
Análise da Coluna: GPA
--------------------------------------------------
Valores Únicos:
[2.92919559 3.04291483 0.11260225 ... 1.14233288 1.80329676 2.14001388]


Número de Valores Únicos:
2371


Estatísticas Descritivas:
               GPA
count  2392.000000
mean      1.906186
std       0.915156
min       0.000000
25%       1.174803
50%       1.893393
75%       2.622216
max       4.000000


Moda:
0    0.0
Name: GPA, dtype: float64


Mediana:
1.8933926937866847


==================================================
Análise da Coluna: GradeClass
--------------------------------------------------
Valores Únicos:
[2. 1. 4. 3. 0.]


Número de Valores Únicos:
5


Estatísticas Descritivas:
        GradeClass
count  2392.000000
mean      2.983696
std       1.233908
min       0.000000
25%       2.000000
50%       4.000000
75%       4.000000
max       4.000000


Moda:
0    4.0
Name: GradeClass, dtype: float64


Mediana:
4.0


==================================================

### Aproximando valores da coluna "StudyTimeWeekly"

In [ ]:
df_student_performance['StudyTimeWeeklyRounded'] = df_student_performance['StudyTimeWeekly'].round(0)

print(f"Análise da Coluna: 'StudyTimeWeeklyRounded'")
print("-" * 50)

# Valores únicos
unique_values = df_student_performance['StudyTimeWeeklyRounded'].unique()
print("Valores Únicos:")
print(unique_values)
print('\n')

# Contar número de valores únicos
num_unique_values = df_student_performance['StudyTimeWeeklyRounded'].nunique()
print("Número de Valores Únicos:")
print(num_unique_values)
print('\n')

# Estatísticas descritivas
stat_describe = pd.DataFrame(df_student_performance['StudyTimeWeeklyRounded'].describe())
print("Estatísticas Descritivas:")
print(stat_describe)
print('\n')

# Moda
mode_value = df_student_performance['StudyTimeWeeklyRounded'].mode()
print('Moda:')
print(mode_value)
print('\n')

# Mediana
median_value = df_student_performance['StudyTimeWeeklyRounded'].median()
print('Mediana:')
print(median_value)
print('\n')

print("=" * 50)

Análise da Coluna: 'StudyTimeWeeklyRounded'
--------------------------------------------------
Valores Únicos:
[20. 15.  4. 10.  5.  8. 16. 18. 12. 11.  3. 19.  7.  2.  9. 14.  6. 17.
  0.  1. 13.]


Número de Valores Únicos:
21


Estatísticas Descritivas:
       StudyTimeWeeklyRounded
count             2392.000000
mean                 9.767977
std                  5.669491
min                  0.000000
25%                  5.000000
50%                 10.000000
75%                 14.000000
max                 20.000000


Moda:
0    10.0
Name: StudyTimeWeeklyRounded, dtype: float64


Mediana:
10.0


==================================================